### ISSUE TITLE
Can't add "0" value

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.scenes#54] opened 2020-06-18 13:34 UTC
When setting a value in numbers, it is not possible to set " 0"
![image](https://user-images.githubusercontent.com/37106885/85026402-4d0fcc80-b181-11ea-9519-5102cf6510fe.png)

**Comment by GermanBluefox** [comment] 2020-06-21 08:38
What the type (common.type) has the variable 0_userdata.0.Tests.Boolen_to_grafana?
I cannot reproduce it

**Comment by Anzic23** [comment] 2020-06-21 11:42
> What the type (common.type) has the variable 0_userdata.0.Tests.Boolen_to_grafana?
> I cannot reproduce it

{
  "from": "system.adapter.admin.1",
  "user": "system.user.admin",
  "ts": 1589546358071,
  "common": {
    "name": "Boolen_to_grafana",
    "role": "",
    "type": "number",
    "desc": "Manually created",
    "min": 0,
    "max": 1,
    "def": 0,
    "read": true,
    "write": true,
    "custom": {
      "influxdb.0": {
        "enabled": true,
        "changesOnly": false,
        "debounce": "1000",
        "retention": "31536000",
        "changesRelogInterval": 0,
        "changesMinDelta": 0,
        "storageType": "",
        "aliasId": ""
      }
    }
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "0_userdata.0.Tests.Boolen_to_grafana",
  "type": "state"
}

**Comment by GermanBluefox** [comment] 2020-06-21 13:58
Fixed in 2.0.11

**Closed** 2020-07-08 17:28 UTC
Labels: fixed
