### ISSUE TITLE
blank page after push the move button

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.scenes#159] opened 2022-04-25 13:23 UTC
result 
![grafik](https://user-images.githubusercontent.com/6681528/165097821-627d3d77-c90b-487a-8145-c9eb77cb6f03.png)

from click on button
![grafik](https://user-images.githubusercontent.com/6681528/165097886-5f9f7ba2-dfd9-4df7-a2f7-13c892ef5993.png)

**Comment by MrK-1** [comment] 2022-05-10 08:24
I have the same problem

scenes 2.3.9.

**Comment by reutli** [comment] 2022-07-15 05:27
yes I'm facing the same issue. Tried Safari, Firefox and Chrome, same issue in all Browsers. How to organize the scenes?

@Apollon77 
here the errors from Chrome:

`iobroker.admin@5.3.8
instrument.ts:124 [2022-07-15T05:14:21.662Z] Try to connect
instrument.ts:124 Translate: time
instrument.ts:124 Translate: timeOffset
instrument.ts:124 Translate: time
instrument.ts:124 Translate: timeOffset
instrument.ts:124 Translate: time
instrument.ts:124 Translate: timeOffset
instrument.ts:124 Translate: time
instrument.ts:124 Translate: timeOffset
instrument.ts:124 Translate: time
instrument.ts:124 Translate: timeOffset
instrument.ts:124 Translate: time
instrument.ts:124 Translate: timeOffset
​ iobroker.scenes@2.3.9
​ 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

​ Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
​ Help us to create open source project with reactJS!
​ See you :)
​ [2022-07-15T05:14:32.463Z] Try to connect
​ iobroker.scenes@2.3.9
​ 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

​ Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
​ Help us to create open source project with reactJS!
​ See you :)
socket.io.js:59 [2022-07-15T05:16:19.140Z] Try to connect
​ Array(1)0: Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:84048)
    at http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1553479
    at Object.useMemo (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1014672)
    at t.useMemo (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:949186)
    at t.useDragType (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1553437)
    at t.useRegisteredDragSource (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1541452)
    at t.useDrag (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1541065)
    at Ve (http://192.168.200.5:8081/adapter/scenes/static/js/main.8829a9d6.chunk.js:1:100132)
    at sa (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1008707)
    at Ks (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1061007)
    at Ac (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1048248)
    at jc (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1048176)
    at Ec (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1048039)
    at yc (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1045005)
    at http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:994499
    at t.unstable_runWithPriority (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1071736)
    at Gi (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:994276)
    at Ji (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:994444)
    at Ki (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:994379)
    at Ne (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1065546)
    at Yt (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:972997)length: 1[[Prototype]]: Array(0)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
​ Array(1)
(anonymous) @ 2.7de3299d.chunk.js:2
2.7de3299d.chunk.js:2 Uncaught Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:84048)
    at http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1553479
    at Object.useMemo (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1014672)
    at t.useMemo (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:949186)
    at t.useDragType (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1553437)
    at t.useRegisteredDragSource (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1541452)
    at t.useDrag (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1541065)
    at Ve (http://192.168.200.5:8081/adapter/scenes/static/js/main.8829a9d6.chunk.js:1:100132)
    at sa (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1008707)
    at Ks (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1061007)
    at Ac (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1048248)
    at jc (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1048176)
    at Ec (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1048039)
    at yc (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1045005)
    at http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:994499
    at t.unstable_runWithPriority (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1071736)
    at Gi (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:994276)
    at Ji (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:994444)
    at Ki (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:994379)
    at Ne (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1065546)
    at Yt (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:972997)
​ iobroker.scenes@2.3.9
​ 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

​ Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
​ Help us to create open source project with reactJS!
​ See you :)
​ [2022-07-15T05:16:27.490Z] Try to connect
instrument.ts:124 [ADAPTERS] getAdapters
instrument.ts:124 [ADAPTERS] getAdaptersInfo
instrument.ts:124 [ADAPTERS] Render
:8081/adapter/ws/ws.png:1          Failed to load resource: the server responded with a status of 404 (Not Found)
raw.githubusercontent.com/instalator/ioBroker.vis-players/master/admin/players.png:1          Failed to load resource: the server responded with a status of 404 ()
instrument.ts:124 getInstances: 10
index.js:16 iobroker.scenes@2.3.9
Prompt.js:15 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

Prompt.js:16 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
Prompt.js:17 Help us to create open source project with reactJS!
Prompt.js:18 See you :)
socket.io.js:59 [2022-07-15T05:17:19.286Z] Try to connect
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
instrument.ts:125 [Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapte…]
(anonymous) @ instrument.ts:125
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Mc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:252
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
index.ts:28 Uncaught Invariant Violation: spec.type must be defined
    at t.invariant (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:84048)
    at http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1553479
    at Object.useMemo (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1014672)
    at t.useMemo (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:949186)
    at t.useDragType (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1553437)
    at t.useRegisteredDragSource (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1541452)
    at t.useDrag (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1541065)
    at Ve (http://192.168.200.5:8081/adapter/scenes/static/js/main.8829a9d6.chunk.js:1:100132)
    at sa (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1008707)
    at Ks (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1061007)
    at Ac (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1048248)
    at jc (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1048176)
    at Ec (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1048039)
    at yc (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1045005)
    at http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:994499
    at t.unstable_runWithPriority (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1071736)
    at Gi (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:994276)
    at Ji (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:994444)
    at Ki (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:994379)
    at Ne (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:1065546)
    at Yt (http://192.168.200.5:8081/adapter/scenes/static/js/2.7de3299d.chunk.js:2:972997)
t.invariant @ index.ts:28
(anonymous) @ useDragType.ts:11
useMemo @ react-dom.production.min.js:172
t.useMemo @ react.production.min.js:23
t.useDragType @ useDragType.ts:9
t.useRegisteredDragSource @ useRegisteredDragSource.ts:16
t.useDrag @ useDrag.ts:37
Ve @ ScenesList.js:60
sa @ react-dom.production.min.js:157
Ks @ react-dom.production.min.js:267
Ac @ react-dom.production.min.js:250
jc @ react-dom.production.min.js:250
Ec @ react-dom.production.min.js:250
yc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73`

**Comment by reutli** [comment] 2022-07-15 05:30
faced with a second issue regarding this topic: After pushing the button and refresh the previously created folder was gone. Done this several times to reproduce.

way to reproduce:
1. create a folder
2. hit "move"-button
3. refresh (as we've got a bank page)
4. folder is gone

**Comment by reutli** [comment] 2022-07-19 09:14
last version which acts correctly: 2.3.3

**Comment by reutli** [comment] 2022-07-20 08:47
push

**Comment by jbubik** [comment] 2022-07-24 16:24
This bug is a duplicate of #124

**Comment by reutli** [comment] 2022-07-25 13:20
> This bug is a duplicate of #124

That's right, but I'm asking myself if a solution will be provided short hand, since issue open since April this year...

**Comment by reutli** [comment] 2022-07-25 13:21
> This is expected. Folders are not stored in the database. They are created on-the-fly when you open the page. Names of folders come from existing scenes. The list lives in your session. Once you leave the page, the list is forgotten. When you come back a new list is generated from scene names. Therefore empty folders don't survive. Reproducible by creating an empty folder and doing refresh.

ok, got it. So this is no issue, it's a normal browser behavior.

**Comment by jbubik** [comment] 2022-07-25 13:42
> That's right, but I'm asking myself if a solution will be provided short hand, since issue's open since April this year...
#124 is open since Sep 2021. In the future, please do not open new issues for the same bug. Add your findings to the original issue. It helps the developers find all relevant pieces in one place. This is open source world, no deadlines, no promises, no SLAs. But everyone can step-up and help. So thanks reutli for sharing and good luck in your projects!

**Comment by reutli** [comment] 2022-07-25 13:51
> > That's right, but I'm asking myself if a solution will be provided short hand, since issue's open since April this year...
> 
> #124 is open since Sep 2021. In the future, please do not open new issues for the same bug. Add your findings to the original issue. It helps the developers find all relevant pieces in one place. This is open source world, no deadlines, no promises, no SLAs. But everyone can step-up and help. So thanks reutli for sharing and good luck in your projects!

as you can see above, it was not me who opened this issue...

**Comment by jbubik** [comment] 2022-07-25 14:32
@reutli: my apology. You are right.
@arteck: can you please close this as duplicate?

**Comment by arteck** [comment] 2022-07-25 14:53
done

**Closed** 2022-07-25 14:53 UTC
